spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/    

---
server:
  port: 8202
spring:
  profiles: pro
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/    